branches:
  except:
    - debian
dist: trusty
language: python
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - g++
    - cmake
    - libeigen3-dev
env:
  matrix:
    - USE_SRC_EIGEN=false
    - USE_SRC_EIGEN=true USE_EIGEN33=false
    - USE_SRC_EIGEN=true USE_EIGEN33=true
script:
- . ./.travis/common.sh
- pip install .
- nosetests
before_install:
- if [ $USE_SRC_EIGEN = true ] && [ $USE_EIGEN33 = true ]; then ./.travis/dependencies/eigen-3.3; fi
- if [ $USE_SRC_EIGEN = true ] && [ $USE_EIGEN33 = false ]; then ./.travis/dependencies/eigen-3.2; fi
- pip install -r requirements.txt
notifications:
  slack:
    secure: AQEc0L8IPw0G+61qoFZ4ceGVuKP6G+XO9UQpoeAbL4IMwJvTsFtbSerFH9lQih2OEz3+iV1muEye9ISW1GuUIyJReQfZNI+sSpCYfxDTeDDdUseMqpFRp0KazVAAhPNZ+zADANKwMisofwQmBhwz0w+LSZ34nhj0Gm7/OGxiU2E=
